spring.application.name=medique

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


admin.full-name=${ADMIN_FULL_NAME}
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}
admin.phone-number=${ADMIN_PHONE}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
